### ISSUE TITLE
Missing markdown file: sql-server-linux-faq

### ISSUE THREAD

**Issue by agriffard** [MicrosoftDocs/sql-docs.fr-fr#11]
When I click to edit this page:
https://docs.microsoft.com/fr-fr/sql/linux/sql-server-linux-faq

There is no corresponding markdown file:
https://github.com/MicrosoftDocs/sql-docs.fr-fr/blob/live/docs/linux/sql-server-linux-faq.md

**Comment by CeciAc** [comment]
Hello @agriffard 

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and the issue was fixed.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
