### ISSUE TITLE
LAST_NODE usage

### ISSUE THREAD

**Issue by Elloudo** [MicrosoftDocs/sql-docs.fr-fr#124]
Hello!

I am not sure to understand the usage of LAST_NODE and I was not able to help myself with the documentation and did not found any example. 

Can you please provide more explanation and example for LAST_NODE usage in:
- simple_match_pattern
- arbitrary_length_match_last_node_predicate
- arbitrary_length_pattern

Thanks a lot

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 9522c78a-6cdd-c5b0-4b5b-f7c6d0e5a241
* Version Independent ID: 27551083-bb07-638b-a491-7f5e4f94c22c
* Content: [MATCH (SQL Graph) - SQL Server](https://docs.microsoft.com/fr-fr/sql/t-sql/queries/match-sql-graph?view=sql-server-2017)
* Content Source: [docs/t-sql/queries/match-sql-graph.md](https://github.com/MicrosoftDocs/sql-docs.fr-fr/blob/live/docs/t-sql/queries/match-sql-graph.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @shkale-msft
* Microsoft Alias: **shkale**

**Comment by srvbpigh** [comment]
Hello, @Elloudo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/sql-docs #4986](https://github.com/MicrosoftDocs/sql-docs/issues/4986) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @Elloudo, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs/issues/4986. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
